language: node_js
node_js:
  - "v11.14.0"
branches:
  only:
  - master
notifications:
  email:
    recipients:
      - haodedong1996@163.com
    on_success: always # default: change
    on_failure: always # default: alway
cache:
  directories:
  - node_modules
  yarn: true
before_install:
- export TZ='Asia/Shanghai'  # 设置时区
install:
 - npm install -g gitbook-cli
script:
- gitbook build 
deploy:
  provider: pages
  skip-cleanup: true
  keep_history: true
  github-token: $GITHUB_TOKEN
  local-dir: ./_book/ ## 根据情况自定义到静态文件输出目录
  target_branch: master
  repo: haodedong/haodedong.github.io
  verbose: true
  on:
    branch: master

# after_script:
#    - cd /_book
#    - git init
#    - git config user.name "haodedong"
#    - git config user.email "haodedong1996@163.com"
#    - git add .
#    - git commit -m "Update Gitbook By TravisCI With Build $TRAVIS_BUILD_NUMBER"
#    - git remote add origin https://github.com/haodedong/haodedong.github.io.git
#    - git push --force --quiet "https://${GITHUB_TOKEN}@${GH_REF}" master:${P_BRANCH}


